### PR TITLE
Fixed CNF issue when running on IBM JDK

### LINKED ISSUE #359: CNF Exception getting throw when running on IBM JDK
When starting the IS 6.0.0 pack on top of IBM JDK 8 latest version we get the error reported at [1].
The other microservices in the pack are added without an issue. I also tested a micro service sample and it works fine on ibm jdk.
But when come to org.wso2.carbon.uuf.httpconnector.msf4j.UUFMicroservice it throws the reported error.
After that cannot visit the User portal app as well.

Are we supporting IBM jsk 8 for uuf? Any insight on this will be helpful.

[1][https://wso2.org/jira/browse/IDENTITY-5762]

### PR DESCRIPTION
**Pull request by thusithathilina**
This will resolve #359

### CODE REVIEW

**Comment by imesh** [comment]
Thusitha, the code looks good! Would you mind briefly explaining the fix? Thanks!

**Comment by thusithathilina** [comment]
@imesh In the previous releases, we have used some JDK internal classes to change the annotation at the runtime. But that is unstable since JDK internal get change and some other JDKs doesn't contain the same classes. Therefore in this fix we removed that. In the fix I've override some of the BeanConfig methods and borrowed and changed the SwaggerReader class which is responsible for reading the annotations. So that way we can control the reading flow as we want rather than changing the annotation at runtime.

**Comment by imesh** [comment]
Thanks for the explanation Thusitha! A great solution! Let's resolve the above conflict and merge this. Thanks!

**Comment by thusithathilina** [comment]
https://github.com/wso2/msf4j/pull/393 will address this

**Pull request closed without merging**
