### PR TITLE
Added the ability to handle HTTP Options requests

### PR DESCRIPTION
**Pull request by janakamarasena**

### CODE REVIEW

**Comment by janakamarasena** [comment]
When merging please close issue #269 HTTP OPTIONS Method

**Comment by afkham** [comment]
This looks great. Can you also add a method to the [StockQuoteService](https://github.com/wso2/msf4j/blob/master/samples/stockquote/fatjar/src/main/java/org/wso2/msf4j/example/StockQuoteService.java) sample which shows the useage of the options method?

**Comment by janakamarasena** [comment]
Since most of the usages for the OPTIONS request is for checking CORS capability I also couldn't think of much of another usage. I added a simple method to check what request types are accepted to a Request-URI. [StockQuoteService](https://github.com/janakamarasena/msf4j/commit/c144ccc3ee83acf3fe1759061f3f0cc7d8738007)

**Comment by afkham** [comment]
There are build failures:
/Users/azeez/projects/github/wso2/msf4j/core/src/main/java/org/wso2/msf4j/internal/router/HttpResourceModel.java:46: error: Wrong order for 'javax.ws.rs.OPTIONS' import.
/Users/azeez/projects/github/wso2/msf4j/core/src/main/java/org/wso2/msf4j/internal/router/MicroserviceMetadata.java:37: error: Wrong order for 'javax.ws.rs.OPTIONS' import.
/Users/azeez/projects/github/wso2/msf4j/core/src/main/java/org/wso2/msf4j/internal/router/Util.java:24: error: Wrong order for 'javax.ws.rs.OPTIONS' import.

----

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.700s
[INFO] Finished at: Mon Sep 12 11:47:45 IST 2016
[INFO] Final Memory: 53M/514M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project msf4j-core: Failed during checkstyle execution: There are 3 errors reported by Checkstyle 6.11.2 with https://raw.githubusercontent.com/wso2/code-quality-tools/master/checkstyle/checkstyle.xml ruleset. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :msf4j-core

**Comment by janakamarasena** [comment]
Fixed the checkstyle errors

**Pull request merged**
